linters:
  ColorKeyword:
    enabled: false
  Comment:
    enabled: false
  Compass::*:
    enabled: true # Disabled by default.
  Compass::PropertyWithMixin:
    ignore:
      - 'inline-block' # Only needed for IE7/FF2 and earlier.
  EmptyLineBetweenBlocks:
    ignore_single_line_blocks: false
  IdSelector:
    enabled: false
  MergeableSelector:
    force_nesting: true
  NameFormat:
    convention: BEM
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    extra_properties:
      - '*background'
      - '*background-image'
      - '*display'
      - '*font-family'
      - '_font-family'
      - '*height'
      - '*list-style-image'
      - '*margin-left'
      - '*margin-right'
      - '*overflow'
      - '*position'
      - '*vertical-align'
      - '*width'
      - '*zoom'
  QualifyingElement:
    enabled: false
  SelectorFormat:
    enabled: false
    convention: BEM
  Shorthand:
    enabled: false
  SingleLinePerProperty:
    allow_single_line_rule_sets: false
  SpaceAfterComma:
    enabled: false
  SpaceAfterPropertyColon:
    style: at_least_one_space
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    enabled: false
  VendorPrefixes:
    enabled: false
  ZeroUnit:
    enabled: false
